// This is generated by writeCoreProposal; please edit!
/* eslint-disable */

const manifestBundleRef = {bundleID:"b1-c714f6c9fb8c3a7c013da3891f4bee34d26f837f528b2a6e586c833d353cb388323a4289cad33f7bfbfa6119764356f3fd3a2b8f0dd32dce1bfb8c80a63144ca"};
const getManifestCall = harden([
  "getManifestForAddAssetToVault",
  {
    debtLimitValue: undefined,
    interchainAssetOptions: {
      decimalPlaces: 6,
      denom: "ibc/3CC19CEC7E5A3E90E78A5A9ECC5A0E2F8F826A375CF1E096F4515CF09DA3E366",
      initialPrice: undefined,
      issuerBoardId: undefined,
      issuerName: "DOT",
      keyword: "DOT",
      oracleBrand: "DOT",
      proposedName: "DOT",
    },
    interestRateValue: undefined,
    scaledPriceAuthorityRef: {
      bundleID: "b1-587b350188c4e6ae05cfea0dd0e72497e649dbf3320137c4ea66f3beafbc2cebc3ad5cb3475e0e6b79f7b3aec61ec9ff3fca4be38b1874e9394a0f359e646c12",
    },
  },
]);
const overrideManifest = {
  addAssetToVault: {
    brand: {
      consume: {
        IST: true,
      },
    },
    consume: {
      agoricNamesAdmin: true,
      auctioneerKit: "auctioneer",
      vaultFactoryKit: "vaultFactory",
    },
    instance: {
      consume: true,
    },
  },
  publishInterchainAssetFromBank: {
    consume: {
      agoricNamesAdmin: true,
      bankManager: true,
      bankMints: true,
      reserveKit: true,
      startUpgradable: true,
      vBankKits: true,
    },
    installation: {
      consume: {
        mintHolder: true,
      },
    },
    produce: {
      bankMints: true,
      vBankKits: true,
    },
  },
  registerScaledPriceAuthority: {
    consume: {
      agoricNamesAdmin: true,
      priceAuthority: true,
      priceAuthorityAdmin: true,
      scaledPriceAuthorityKits: true,
      startUpgradable: true,
    },
    installation: {
      consume: {
        scaledPriceAuthority: true,
      },
    },
    produce: {
      scaledPriceAuthorityKits: true,
    },
  },
};

// Make the behavior the completion value.
(({
  manifestBundleRef,
  getManifestCall,
  overrideManifest,
  E,
  log = console.info,
  restoreRef: overrideRestoreRef,
}) => {
  const { entries, fromEntries } = Object;

  // deeplyFulfilled is a bit overkill for what we need.
  const shallowlyFulfilled = async obj => {
    if (!obj) {
      return obj;
    }
    const ents = await Promise.all(
      entries(obj).map(async ([key, valueP]) => {
        const value = await valueP;
        return [key, value];
      }),
    );
    return fromEntries(ents);
  };

  /** @param {ChainBootstrapSpace & BootstrapPowers & { evaluateBundleCap: any }} allPowers */
  const behavior = async allPowers => {
    // NOTE: If updating any of these names extracted from `allPowers`, you must
    // change `permits` above to reflect their accessibility.
    const {
      consume: { vatAdminSvc, zoe, agoricNamesAdmin },
      evaluateBundleCap,
      installation: { produce: produceInstallations },
      modules: {
        utils: { runModuleBehaviors },
      },
    } = allPowers;
    const [exportedGetManifest, ...manifestArgs] = getManifestCall;

    /** @type {(ref: import\('./externalTypes.js').ManifestBundleRef) => Promise<Installation<unknown>>} */
    const defaultRestoreRef = async ref => {
      // extract-proposal.js creates these records, and bundleName is
      // the name under which the bundle was installed into
      // config.bundles
      const p =
        'bundleName' in ref
          ? E(vatAdminSvc).getBundleIDByName(ref.bundleName)
          : ref.bundleID;
      const bundleID = await p;
      const label = bundleID.slice(0, 8);
      return E(zoe).installBundleID(bundleID, label);
    };
    const restoreRef = overrideRestoreRef || defaultRestoreRef;

    // Get the on-chain installation containing the manifest and behaviors.
    console.info('evaluateBundleCap', {
      manifestBundleRef,
      exportedGetManifest,
      vatAdminSvc,
    });
    let bcapP;
    if ('bundleName' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getNamedBundleCap(manifestBundleRef.bundleName);
    } else {
      bcapP = E(vatAdminSvc).getBundleCap(manifestBundleRef.bundleID);
    }
    const bundleCap = await bcapP;

    const manifestNS = await evaluateBundleCap(bundleCap);

    console.error('execute', {
      exportedGetManifest,
      behaviors: Object.keys(manifestNS),
    });
    const {
      manifest,
      options: rawOptions,
      installations: rawInstallations,
    } = await manifestNS[exportedGetManifest](
      harden({ restoreRef }),
      ...manifestArgs,
    );

    // Await references in the options or installations.
    const [options, installations] = await Promise.all(
      [rawOptions, rawInstallations].map(shallowlyFulfilled),
    );

    // Publish the installations for behavior dependencies.
    const installAdmin = E(agoricNamesAdmin).lookupAdmin('installation');
    await Promise.all(
      entries(installations || {}).map(([key, value]) => {
        produceInstallations[key].resolve(value);
        return E(installAdmin).update(key, value);
      }),
    );

    // Evaluate the manifest for our behaviors.
    return runModuleBehaviors({
      allPowers,
      behaviors: manifestNS,
      manifest: overrideManifest || manifest,
      makeConfig: (name, _permit) => {
        log('coreProposal:', name);
        return { options };
      },
    });
  };

  // Make the behavior the completion value.
  return behavior;
})({ manifestBundleRef, getManifestCall, overrideManifest, E });
